[package]
name = "shanshui_preview"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-graphics = "0.8.1"
fixed = { version = "1.29.0", default-features = false }
image = { version = "0.25.6", default-features = false, features = ["png"] }
