[package]
name = "meditamer"
version = "0.1.0"
authors = ["Dimitri Fedorov <dimitri.fedorov@suprematic.net>"]
edition = "2021"
resolver = "2"
rust-version = "1.81"

[[bin]]
name = "meditamer"
harness = false    # do not use the built in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = ["std", "esp-idf-sys/native"]

pio = ["esp-idf-sys/pio"]
std = ["esp-idf-sys/binstart", "esp-idf-sys/std"]
alloc = []
nightly = []
experimental = []
embassy = []

[dependencies]
esp-idf-sys = { version = "0.36.1", default-features = false }
port-expander = { version = "0.6.5", features = ["std"] }
embedded-hal = "1.0.0"
embedded-hal-bus = { version = "0.3.0", features = ["std"] }
embedded-graphics = "0.8.1"
anyhow = "1.0.101"
lazy_static = "1.5.0"
u8g2-fonts = "0.7.2"

[build-dependencies]
embuild = "0.33.1"
