[package]
name = "sdcard"
version = "0.1.0"
edition = "2021"
rust-version = "1.88"

[dependencies]
embassy-time = "0.5.0"
esp-hal = { version = "1.0.0", features = ["esp32", "unstable"] }
esp-println = { version = "0.16.1", default-features = false, features = ["esp32", "log-04", "uart"] }
heapless = "0.8.0"
